const article = require('./article')
const user = require('./user')
const sys = require('./sys')
// const root = require('./root')
// const chartGPT = require('./openai')
const file = require('./file')
const preject = require('./preject')
const admin = require('./admin')
const demand = require('./demand')
const easyHouse = require('./easyHouse')
const pastBooks = require('./pastBooks')
const jianli = require('./jianli')

module.exports = (app) => {
  app.use('/api/post', article)
  app.use('/api/user', user)
  // app.use('/api/user', root)
  app.use('/api/sys', sys)
  // app.use('/api/open-ai', chartGPT)
  app.use('/api/file', file)
  app.use('/api/preject', preject)
  app.use('/api/admin', admin)
  app.use('/api/demand', demand)
  app.use('/api/easyHouse', easyHouse)
  app.use('/api/pastBooks', pastBooks)
  app.use('/api/jianli', jianli)
}
