export const menu = [
  {
    parent: null,
    id: 0,
    text: '文章管理',
    icon: 'mdi-credit-card',
    scr: 'article',
    children: [
      {
        parent: 0,
        id: 0,
        text: '标签管理',
        icon: 'mdi-label',
        path: 'catptchs',
        scr: 'catptchs',
      },
      {
        parent: 0,
        id: 1,
        text: '文章列表',
        icon: 'mdi-format-list-bulleted',
        path: 'list',
        scr: 'list',
      },
    ],
  },
  {
    parent: null,
    id: 1,
    text: '作品管理',
    icon: 'mdi-compass-rose',
    scr: 'preject',
    children: [],
  },
  {
    parent: null,
    id: 1,
    text: '用户管理',
    icon: 'mdi-compass-rose',
    scr: 'preject',
    children: [
      {
        parent: null,
        id: 1,
        text: '用户列表',
        icon: 'mdi-compass-rose',
        path: 'user',
      },
    ],
  },
  {
    parent: null,
    id: 1,
    text: '系统管理',
    icon: 'mdi-cog',
    scr: 'system',
    children: [
      {
        parent: null,
        id: 1,
        text: '关于',
        icon: 'mdi-cog',
        path: 'about',
        scr: 'about',
      },
      {
        parent: null,
        id: 1,
        text: '菜单管理',
        icon: 'mdi-menu',
        path: 'menus',
        scr: 'menus',
      },
    ],
  },
]
